[package]
name = "cw-vesting"
authors = ["Jake Hartnell", "ekez <ekez@withoutdoing.com>", "blue-note"]
description = "A CosmWasm vesting contract."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

# configure different optimizer builds for whether or not staking is enabled by
# the chain
[package.metadata.optimizer]
standard-build = false
builds = [
  { name = "staking", features = [
    "staking",
  ], default-features = false },
  { name = "no_staking", features = [
  ], default-features = false },
]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["staking"]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []
# enable staking features on chains that support staking. most do, so this is a
# default. Neutron does not, for example.
staking = ["cosmwasm-std/staking"]

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-denom = { workspace = true }
cw-ownable = { workspace = true }
cw-stake-tracker = { workspace = true }
cw-storage-plus = { workspace = true }
cw-utils = { workspace = true }
cw-wormhole = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
wynd-utils = { workspace = true }

[dev-dependencies]
cw-vesting = { workspace = true }
anyhow = { workspace = true }
cw-multi-test = { workspace = true }
cw20-base = { workspace = true }
dao-testing = { workspace = true }
